spring.application.name=backend

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bookstore?useUnicode=true&characterEncoding=UTF-8

spring.datasource.username=root

spring.datasource.password=

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=none

# JWT Configuration
jwt.secret=9a6727255074f03a6a96e95bdf57b420084f884f884f884f884f884f884f884f
jwt.expiration=86400000